export type FaqItem = { question: string; answer: string };
export type FaqCategory = { title: string; items: FaqItem[] };

export const faqCategories: FaqCategory[] = [
 { title: 'What is Hot Apple Gin?', items: [
  { question: 'What is Hot Apple Gin?', answer: "A warm cocktail in a bottle. Gin-based, apple-forward, served heated, built for the months when a gin & tonic feels like a missed opportunity. It started as a family recipe, became a brand somewhat against its own intentions, and hasn't looked back since." },
  { question: 'Is Hot Apple Gin a gin?', answer: "Gin is the foundation, yes. But this isn't a gin you mix or serve over ice. Hot Apple Gin is a ready-to-drink cocktail, pre-blended, fully finished, designed to be heated and poured. The gin was developed specifically for this recipe." },
  { question: 'What is a warm cocktail RTD?', answer: 'RTD stands for ready-to-drink, a cocktail that comes fully assembled. Hot Apple Gin is a warm RTD: you heat it, pour it, and hand it to someone. No jiggers, no blenders, no bartending diploma. The warm RTD category is growing fast globally, and Hot Apple Gin sits at the higher end, which is the only end we were ever interested in.' },
  { question: 'What makes Hot Apple Gin different from mulled wine?', answer: 'Mulled wine is wine-based, heavier, tannic, and usually very sweet. Hot Apple Gin is built on gin and apple, which makes it lighter, cleaner, and considerably more interesting. Same temperature. Different category entirely.' },
  { question: 'What makes Hot Apple Gin different from mulled cider?', answer: 'Mulled cider is fermented apple juice with spices thrown in, rustic, simple, and fine for what it is. Hot Apple Gin is a crafted cocktail with a recipe that took two winters to get right. If cider is the casual end of the apple spectrum, Hot Apple Gin is the other end entirely.' },
  { question: 'What makes Hot Apple Gin different from regular cider?', answer: "Cold cider is a summer drink, fizzy, refreshing, uncomplicated. Hot Apple Gin is warm, still, gin-based, and built for entirely different weather. Apple is the only thing they share. Beyond that, they're not really in the same conversation." },
  { question: 'What makes Hot Apple Gin different from a regular gin & tonic?', answer: 'Season, temperature, and intent. A G&T is cold, sparkling, and built for a terrace in July. Hot Apple Gin is warm, still, and built for the other half of the year. Same spirit at the core, completely different experience. Both have their place. This one just has better timing in winter.' },
  { question: 'Is Hot Apple Gin a seasonal product or available year-round?', answer: "Seasonal. Hot Apple Gin is made for colder months, autumn, winter, Christmas markets, slow evenings that stretch into something unplanned. It's not available year-round. Scarcity, as it turns out, suits it." },
  { question: "I don't like gin. Is Hot Apple Gin still for me?", answer: "Yes. The gin works in the background, it adds depth, botanicals, and a finish that apple juice alone could never pull off. But it doesn't announce itself. People who claim they don't like gin have been enjoying Hot Apple Gin all evening without bringing it up once. Knowing you, you will be one of them." },
  { question: 'I love gin. Is Hot Apple Gin for me?', answer: "Then you'll appreciate exactly what's in it. A Dutch gin developed specifically for this recipe, not an afterthought, not an off-the-shelf base. It's there in every sip. You'll just be the person at the table who notices." },
  { question: "I've seen other warm apple drinks, is that the same thing?", answer: "There are plenty of warm apple drinks. We've heard there are even a few that call themselves something similar. There is one Hot Apple Gin. Easy to recognise. Hard to forget." }
 ]},
 { title: 'Taste & Ingredients', items: [
  { question: 'What does Hot Apple Gin taste like?', answer: 'Warm apple up front, built on a blend of pressed apple varieties. Botanical depth from the gin underneath. A layered spice finish that lingers without overstaying its welcome. And an aroma, the moment it starts heating, that does half the work before anyone takes a sip.' },
  { question: "Isn't it just warm apple juice?", answer: 'You could gather your family, heat some apple juice, and add a good gin. And then spend the rest of the evening explaining to everyone why you thought that was the same thing. Hot Apple Gin is built on a carefully developed blend of apple varieties, a Dutch gin crafted specifically for this recipe, and a spice balance that took two full winters to get right. Warm apple juice is a fine drink. This is something else.' },
  { question: 'Is Hot Apple Gin sweet?', answer: 'Sweet enough to be inviting. Not sweet enough to be a problem. The apple gives it warmth and roundness; the gin botanicals and spices keep it from tipping into dessert territory. Most people who expect something syrupy are pleasantly surprised.' },
  { question: 'Does Hot Apple Gin contain real apple juice?', answer: 'Yes. The base is a blend of pressed apple varieties, different apples bring different things to the flavour, and the blend was chosen carefully. On top of that: gin, and a spice recipe that took two full winters to finalise.' },
  { question: 'What ingredients are used in Hot Apple Gin?', answer: "A blend of apple juices from multiple varieties, Dutch gin developed specifically for this recipe, and a spice blend that we're not going to fully disclose, not out of secrecy, but because two winters of trial and error deserve a little mystery." },
  { question: 'What is the exact recipe?', answer: "We could tell you. But then we'd have to kill you. Two winters of testing, a spice blend developed from scratch, and a gin built specifically for this recipe, that's as far as we go. Buy the bottle. It's easier." },
  { question: 'Does Hot Apple Gin contain caffeine?', answer: 'No. The warmth is all natural.' },
  { question: 'How many calories does Hot Apple Gin contain?', answer: 'Calorie information is available on the product label. At 4.1% ABV, the caloric load per serving is well below most full-strength spirits or cocktails. Something to keep in mind when someone at the table inevitably asks.' }
 ]},
 { title: 'Alcohol & Dietary', items: [
  { question: 'How much alcohol does Hot Apple Gin contain?', answer: 'The original is 4.1% ABV, comparable to a strong beer. The 0.0 version contains no alcohol. Two bottles, same ritual, different morning after.' },
  { question: 'Is 4.1% ABV considered low alcohol?', answer: 'Yes, low-alcohol by most regulatory and consumer standards. It was a deliberate choice. The warmth, the aroma, and the ritual don\'t depend on high ABV. You can have a full evening without the kind of decisions you regret by Tuesday.' },
  { question: 'Is there an alcohol-free version of Hot Apple Gin?', answer: "Yes. Hot Apple Gin 0.0, all the warmth, none of the alcohol. Same apple blend, same spices, same aroma when it heats. It's not a compromise; it's the same drink with a different ending. Available via The Collection." },
  { question: 'What does Hot Apple Gin 0.0 taste like?', answer: 'Warm, layered, and worth slowing down for. The apple and spice profile is fully intact. Whether you\'re skipping alcohol by choice or by circumstance, the experience holds. Some people prefer it. We understand why. See The Collection.' },
  { question: 'Is Hot Apple Gin vegan?', answer: 'Yes. No animals were harmed in the making of this cocktail. Only a few apples.' },
  { question: 'Is Hot Apple Gin gluten-free?', answer: "Hot Apple Gin does not contain gluten-containing ingredients. If you have celiac disease or a serious intolerance, refer to the product label for full details, production environments can vary and we'd rather you check than assume." },
  { question: 'Does Hot Apple Gin contain allergens?', answer: "Full allergen information is on the product label. If you have a specific allergy, check the label or contact us before consuming. We'd rather answer a question than cause a problem." }
 ]},
 { title: 'How to Serve & Heat', items: [
  { question: 'How is Hot Apple Gin served?', answer: "Heated. Poured into a stemmed glass. Garnished with a slice of apple and, if you're doing it properly, a whisper of spice. Five steps, none of them difficult. The full ritual is on The Serve, and it's worth following." },
  { question: 'What is the ideal serving temperature?', answer: 'Warm, not boiling. Heat it gently until the first steam rises, somewhere around 65-70°C. Hot enough that the aroma fills the room. Cool enough that nobody burns their lip. That window is smaller than it sounds, but easier to hit than it reads.' },
  { question: 'Can Hot Apple Gin also be served cold?', answer: "It's called Hot Apple Gin for a reason. You could serve it cold, just as you could serve champagne warm. We're not here to judge. We are here to note that some names exist for a purpose." },
  { question: 'How do I heat Hot Apple Gin at home?', answer: "Pan, low to medium heat, stir gently, remove when steam appears. That's it. No boiling, you're making a cocktail, not a reduction. Full step-by-step on The Serve." },
  { question: 'Can Hot Apple Gin be heated in a microwave?', answer: "You can. But a pan takes two minutes and the result is noticeably better. Microwaves heat unevenly and it's easy to overshoot. Some shortcuts aren't worth the extra thirty seconds they save." },
  { question: 'Can Hot Apple Gin be heated in a pan?', answer: "Yes, and it's the recommended method. Low to medium heat, gentle stir, off the heat the moment steam appears. Simple enough that there's no excuse for getting it wrong." },
  { question: 'Can Hot Apple Gin be served in batches for parties?', answer: 'Yes. Heat the full litre in a pan, or scale up with multiple bottles in a larger pot. Keep it on the lowest setting to hold temperature without boiling. A ladle and enough glasses is all the equipment you need. Batch-serving is actually where it shines, the aroma in the room does the marketing for you.' },
  { question: 'What garnish works best with Hot Apple Gin?', answer: "A thin slice of fresh apple is the classic. A light dusting of spice adds to the visual. The garnish matters, it should look as good as it smells, because people will be looking before they're drinking." },
  { question: 'Should I add extra spices?', answer: 'The spice blend is already in the recipe, nothing needs to be added. A dusting of spice as garnish is a presentation choice, not a flavour correction. The drink is finished before it reaches you.' },
  { question: 'Which glass should I use?', answer: "A stemmed glass, wine glass or coupe. The stem keeps your hand away from the heat. It also makes it feel like the occasion it is. A heat-safe mug works if that's what you have. But a proper glass makes a difference. It always does." },
  { question: 'Can Hot Apple Gin be used in cocktails or mixed drinks?', answer: "It's a complete cocktail as bottled. You could add things to it. Some people add ketchup to a perfect steak. We're not here to stop you, just to note that some things are perfect by themselves." },
  { question: 'Can Hot Apple Gin be used in cooking or desserts?', answer: 'Yes, and it\'s a better idea than it might sound. Warm apple and spice translates well into glazes for duck or pork, poached pear syrups, or spiced cake batters. The alcohol cooks off. The flavour stays.' }
 ]},
 { title: 'Occasions & Events', items: [
  { question: 'Is Hot Apple Gin suitable for Christmas markets and winter events?', answer: "It was practically designed for them. Portable, easy to batch-heat, and the aroma alone draws people in before a word is said. We know, we started at a Christmas market. We ran out twice on the first day. We've never forgotten it." },
  { question: 'Can Hot Apple Gin be served at ski lodges or après-ski bars?', answer: "It belongs there. Warm, layered, low-alcohol enough to keep you functional on the mountain. It heats quickly, the batch-serve format works perfectly for a busy lodge, and it's the kind of drink people talk about after. That's not a small thing." },
  { question: 'Is Hot Apple Gin suitable as a welcome drink?', answer: "Yes. A warm welcome drink in winter makes a statement that cold Prosecco doesn't. Served properly, stemmed glass, garnish in place, it sets the tone before anyone's sat down." },
  { question: 'Can Hot Apple Gin be used in horeca or catering?', answer: 'Yes. Simple to prepare, consistent in quality, and the kind of serve that makes a menu memorable. Hot Apple Gin works across hospitality environments, from hotel lounges to catering operations to restaurant wine lists with ambition. More on the Partnerships page.' },
  { question: 'What are the best occasions to serve Hot Apple Gin?', answer: "Cold evenings with people you don't want to leave. Christmas dinners, winter terraces, ski lodges, corporate events where another bottle of prosecco would have been the easy, and wrong, choice. Anywhere warmth matters, literally or otherwise." }
 ]},
 { title: 'Storage & Shelf Life', items: [
  { question: 'How should I store Hot Apple Gin?', answer: 'Cool, dark, upright. A cupboard or pantry is fine. No refrigeration required before opening.' },
  { question: 'Does Hot Apple Gin need to be refrigerated?', answer: "Not before opening. After opening, the fridge extends shelf life, and at 4.1% ABV, shelf life after opening is shorter than a full-strength spirit. Treat it like a fancy juice with a gin problem." },
  { question: 'What is the shelf life of an unopened bottle?', answer: 'The best-before date is on the bottle. Store it correctly and it keeps well throughout. Buying it and then forgetting about it for a year is not a storage strategy we recommend.' },
  { question: 'How long does Hot Apple Gin keep after opening?', answer: "A few weeks at room temperature, longer in the fridge. Low ABV means it won't last indefinitely once air gets in. The practical advice: don't leave much in the bottle. Problem solved." },
  { question: 'Can I reheat Hot Apple Gin multiple times?', answer: "Once or twice is fine. Repeated heating degrades the flavour and flattens the aroma. Better to heat only what you'll drink in one sitting. This is not a difficult discipline to maintain." }
 ]},
 { title: 'Orders & Shipping', items: [
  { question: 'In which countries is Hot Apple Gin available?', answer: "Online ordering is available internationally, and our retail footprint is expanding each season. For current availability in your country, check the webshop or contact us directly. We're working on being somewhere near you, sooner than you'd expect." },
  { question: 'How long does delivery take?', answer: "Within the Netherlands, typically 1-3 business days. International orders vary by destination, you'll see an estimated timeframe at checkout. If you're ordering from far away: we appreciate the effort." },
  { question: 'What are the shipping costs?', answer: 'Calculated at checkout based on location and order size. Free shipping thresholds may apply, check the webshop for current conditions.' },
  { question: 'Can I track my order?', answer: "Yes. A tracking link arrives by email once your order ships. If it hasn't appeared, check spam first, then reach out. We'll sort it." },
  { question: 'What happens if my bottle arrives damaged?', answer: "That shouldn't happen. If it does: contact us with a photo and your order details. We'll make it right, no debate required." },
  { question: 'Can I return my order?', answer: "Returns follow applicable consumer protection rules. If something isn't right, reach out, we'd rather resolve it than leave you with a problem." }
 ]},
 { title: 'Gifts & Gift Sets', items: [
  { question: 'Does Hot Apple Gin offer gift sets?', answer: "Yes, and they're gifts people actually remember. The Original Gift Set pairs Hot Apple Gin with everything needed for the full ritual. The 0.0 Gift Set does the same, without the alcohol. Both are available via The Collection. For people worth opening the good glassware for." },
  { question: 'Can I add a personal message to a gift order?', answer: 'Yes. A personal message option is available at checkout. Keep it short or make it count, your call.' },
  { question: 'Do you offer gift wrapping?', answer: "The packaging arrives ready to give. If you have specific requirements beyond that, contact us before ordering and we'll see what's possible." },
  { question: 'Is Hot Apple Gin suitable as a corporate gift?', answer: "It is, and it's one that gets remembered, which is the point of a corporate gift. Warm, distinctive, and not another bottle of wine someone will open on a Tuesday. Available in bottles and gift sets, with options for larger orders. Reach out via the Partnerships page." }
 ]},
 { title: 'Business & Wholesale', items: [
  { question: 'Do you supply bars, restaurants, and hotels?', answer: 'Yes. Hot Apple Gin is built for places that value the moment, hotel lounges, restaurant menus with a point of view, winter terraces that want something worth ordering. We work with partners who care about the serve, not just the margin. More on the Partnerships page.' },
  { question: 'Do you work with distributors?', answer: "Yes, and we're actively expanding. If you represent a distribution company and see a fit, we want to hear from you. Get in touch via Partnerships." },
  { question: 'Can I sell Hot Apple Gin in my store?', answer: "Retail and specialist liquor stores are part of our partner network. If your shelves have room for something that earns its place, let's talk. Start via Partnerships." },
  { question: 'Do you offer bulk or wholesale pricing?', answer: "We don't publish a price list, we build partnerships. Good things start with a conversation, and we take care of the people we work with. Reach out via Partnerships and we'll take it from there." },
  { question: 'Can I serve Hot Apple Gin at festivals or events?', answer: "Yes, seasonal events and festival concepts are close to our roots. Hot Apple Gin started at a Christmas market. If you're planning a winter activation and see a fit, get in touch via Partnerships." },
  { question: 'Do you provide POS or promotional materials?', answer: "We support our partners with brand assets and serving guidance at every touchpoint. Specific POS needs can be discussed when setting up the partnership. We're invested in how it looks in your space, because it reflects on ours." },
  { question: 'Are custom branded collaborations possible?', answer: "Possibly. We're selective, a bad fit benefits nobody. If you have a concept that makes sense, we're listening." },
  { question: 'How can I request more information about wholesale or partnerships?', answer: 'Via the Partnerships page, or through the contact form. We prefer a real conversation to a brochure request.' }
 ]},
 { title: 'Brand & Story', items: [
  { question: 'Where does Hot Apple Gin come from?', answer: 'Haarlem, the Netherlands. The city that gave its name to a neighbourhood in New York, and now gives the world a warm gin cocktail. We consider both a reasonable contribution.' },
  { question: 'Who created Hot Apple Gin?', answer: "No multinational. No R&D department. No focus group. A family, a recipe, and the kind of craftsmanship that doesn't come with an org chart." },
  { question: 'Is Hot Apple Gin a family company?', answer: 'It is a company. But first and foremost, it is a family affair, one that turned into a company. A family company, one might say. The name makes it hard to miss.' },
  { question: 'Why was Hot Apple Gin created?', answer: "Why is the sky blue? Why is the grass green? Some things are just meant to be. A love for making things by hand, a spark of inspiration, and two winters of obsessive refinement, that's how Hot Apple Gin came to exist. We stopped asking why a long time ago." },
  { question: 'Where is Hot Apple Gin produced?', answer: 'In the Netherlands. The gin is developed specifically for this recipe, not sourced, not substituted. Built for it.' },
  { question: 'What inspired the recipe?', answer: "A message. A nudge. A winter experiment that refused to stay an experiment. The full story is on the website, and it's worth two minutes." },
  { question: 'Why do you call it a winter cocktail?', answer: "Because most drinks that claim to work year-round were designed for none of them. Hot Apple Gin was built for cold weather, slow evenings, and the kind of company you don't want to see leave. That's a winter drink." }
 ]},
 { title: 'Sustainability & Packaging', items: [
  { question: 'Can I recycle the Hot Apple Gin bottle?', answer: 'Yes. Glass, fully recyclable. A bottle this well designed deserves a second life, even if that life is as something less interesting.' },
  { question: "What is Hot Apple Gin's approach to sustainability?", answer: "We think about it seriously and don't use it as a marketing headline. Sustainable decisions are built into how we produce and package, not bolted on afterwards. We'll have more to say as we grow, and we'll say it when it's earned." }
 ]},
 { title: 'Find & Follow', items: [
  { question: 'Is Hot Apple Gin available in stores?', answer: 'Retail availability is expanding across Europe each season. The fastest route is always the webshop at hotapplegin.com, international shipping available. If you want it in a specific store near you, let us know. Stockist requests are taken seriously.' },
  { question: 'Where can I buy Hot Apple Gin near me?', answer: "Start at hotapplegin.com. Retail is growing, but the webshop ships internationally and is always the most reliable option. If you're somewhere we haven't reached yet, that's useful information for us." },
  { question: 'Can I visit Hot Apple Gin at trade shows or events?', answer: "Yes, we attend trade shows and seasonal events. Follow us on Instagram for announcements, or sign up via The Collection page. We don't announce things twice." },
  { question: 'Do you offer limited editions?', answer: "The collection is seasonal by nature, and we explore new expressions when the timing is right. Follow along on Instagram or sign up for early access. Limited releases don't have a waiting list, they have a sell-by moment." },
  { question: 'How can I stay updated on new releases?', answer: "Sign up via The Collection page. You'll hear first when Hot Apple Gin returns. We also post on Instagram, @hotapplegin." },
  { question: 'How can I contact the Hot Apple Gin team?', answer: 'Via the Contact page. We read everything. We respond to what deserves a response, which is most of it.' }
 ]}
];
